name: Unit tests
on:
  # Run tests on all pushes to main and on all commits to PRs to all branches ~~the master branch~~
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - '**'
      - opened

jobs:
  unit-tests:
    name: Run unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Test only on Python 3.8 to save compute resources.
        python-version: [3.8]
        # python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/
